### ISSUE TITLE
Animated bullets

### ISSUE THREAD

**Issue by alexwalterbos** [alexwalterbos/mustache-nemesis#16]
Bullets must be animated by switching the texture from frame to frame.

**Comment by AlexKolpa** [comment]
Could you explain? If we're going with the razor blades idea, a uniform rotation would work fine.

**Comment by alexwalterbos** [comment]
It's a requirement from the assignment!

**Comment by AlexKolpa** [comment]
Pfft, but that's boring. Then we should at least use something fancy like a texture atlas or something like that.

**Comment by alexwalterbos** [comment]
Source for razor: http://www.clker.com/cliparts/I/R/9/9/3/Z/razor-blade-hi.png
